import { DATA_SPEAKER } from './speaker.data';
import { v4 as uuidv4 } from 'uuid';

export const DATA_SCHEDULE = [
	{
		uuid: uuidv4(),
		time: '09.00 - 09.30',
		duration: '30',
		agenda: 'Audience Reception',
		pic: 'Event team',
		speakers: [],
		title: null,
		organization: null,
	},
	{
		uuid: uuidv4(),
		time: '09.30 - 09.35',
		duration: '5',
		agenda: 'Opening by MC',
		pic: 'MC',
		speakers: [],
		title: null,
		organization: null,
	},
	{
		uuid: uuidv4(),
		time: '09.35 - 09.45',
		duration: '10',
		agenda: 'Opening',
		pic: 'Event team',
		speakers: [
			{
				name: DATA_SPEAKER['rendra-toro'].name,
				data: DATA_SPEAKER['rendra-toro'],
			},
		],
		title: null,
		organization: 'Indosat Ooredoo Hutchison',
	},
	{
		uuid: uuidv4(),
		time: '09.45 - 10.00',
		duration: '15',
		agenda: 'Opening from Indosat',
		pic: 'Event team',
		speakers: [
			{
				name: 'Indosat Team',
				data: null,
			},
		],
		title: null,
		organization: 'Indosat Ooredoo Hutchison',
	},
	{
		uuid: uuidv4(),
		time: '10.00 - 10.30',
		duration: '30',
		agenda: 'Talk #1 (Keynote)',
		pic: 'Speakership Team',
		speakers: [
			{
				name: 'Angie Sasmita',
				data: DATA_SPEAKER['angie-sasmita'],
			},
		],
		topics: 'UI/UX',
		title: 'Make your Android app come alive with Jetpack Compose Animation',
		organization: 'Google',
	},
	{
		uuid: uuidv4(),
		time: '10.30 - 11.00',
		duration: '30',
		agenda: 'Talk #2',
		pic: 'Speakership Team',
		speakers: [
			{
				name: DATA_SPEAKER['budi-oktaviyan'].name,
				data: DATA_SPEAKER['budi-oktaviyan'],
			},
		],
		topics: 'DevOps Infra',
		title: 'Bazel Build System - The Grab Migration Experience',
		organization: 'GDE/Grab',
	},
	{
		uuid: uuidv4(),
		time: '11.00 - 11.30',
		duration: '30',
		agenda: 'Talk #3',
		pic: 'Speakership Team',
		speakers: [
			{
				name: 'Raditya Gumay',
				data: DATA_SPEAKER['raditya-gumay'],
			},
		],
		topics: 'Performance',
		title: 'Shift left in respect to app performance improvement at Gojek',
		organization: 'Gojek',
	},
	{
		uuid: uuidv4(),
		time: '11.30 - 12.00',
		duration: '30',
		agenda: 'Talk #4',
		pic: 'Speakership Team',
		speakers: [
			{
				name: DATA_SPEAKER['muh-isfhani-ghiath'].name,
				data: DATA_SPEAKER['muh-isfhani-ghiath'],
			},
			{
				name: DATA_SPEAKER['danang-juffry'].name,
				data: DATA_SPEAKER['danang-juffry'],
			},
		],
		topics: 'Compose',
		title: 'Juara Android: Compose!',
		organization: 'GoTo and Google',
	},
	{
		uuid: uuidv4(),
		time: '12.00 - 12.45',
		duration: '45',
		agenda: 'Break',
		pic: 'Logistic Team',
		speakers: [],
		title: null,
		organization: '',
	},
	{
		uuid: uuidv4(),
		time: '12.45 - 13.00',
		duration: '15',
		agenda: 'Ishoma',
		pic: 'Event team',
		speakers: [],
		title: null,
		organization: null,
	},
	{
		uuid: uuidv4(),
		time: '13.00 - 13.30',
		duration: '30',
		agenda: 'Talk #5',
		pic: 'Speakership Team',
		speakers: [
			{
				name: 'Hakim Hauston',
				data: DATA_SPEAKER['hakim-hauston'],
			},
		],
		topics: 'Large Screen',
		title: 'Develop apps for Large screen and foldables',
		organization: 'Google',
	},
	{
		uuid: uuidv4(),
		time: '13.30 - 14.00',
		duration: '30',
		agenda: 'Talk #6',
		pic: 'Speakership Team',
		speakers: [
			{
				name: 'Djaka Pradana Jaya Priambudi',
				data: DATA_SPEAKER['djaka-pradana-jaya-priambudi'],
			},
		],
		topics: 'Architecture',
		title: 'Compose (not a compose UI) for Business Logic',
		organization: 'Traveloka',
	},
	{
		uuid: uuidv4(),
		time: '14.00 - 14.30',
		duration: '30',
		agenda: 'Talk #7',
		pic: 'Speakership Team',
		speakers: [
			{
				name: DATA_SPEAKER['veronica-putri-anggraini'].name,
				data: DATA_SPEAKER['veronica-putri-anggraini'],
			},
		],
		topics: 'Location and Geofence',
		title: 'Geofencing feature to boost your digital campaign',
		organization: 'eWide Plus/Line',
	},
	{
		uuid: uuidv4(),
		time: '14.30 - 15.00',
		duration: '30',
		agenda: 'Talk #8',
		pic: 'Speakership Team',
		speakers: [
			{
				name: DATA_SPEAKER['kelvin-wong'].name,
				data: DATA_SPEAKER['kelvin-wong'],
			},
			{
				name: DATA_SPEAKER['ghiyats-hanif-iskandar'].name,
				data: DATA_SPEAKER['ghiyats-hanif-iskandar'],
			},
		],
		topics: 'Multiplatform',
		title: 'Our key lessons learned in adopting KMM in Android&iOS projects',
		organization: 'NBS',
	},
	{
		uuid: uuidv4(),
		time: '15.00 - 15.30',
		duration: '30',
		agenda: 'Talk #9',
		pic: 'Speakership Team',
		speakers: [
			{
				name: 'Angga Dwi Ariffandi',
				data: DATA_SPEAKER['angga-dwi-arifandi'],
			},
		],
		topics: 'Flutter',
		title: 'GraphQL in Flutter: Why and How',
		organization: 'GDE/Rock',
	},
	{
		uuid: uuidv4(),
		time: '15.30 - 16.00',
		duration: '30',
		agenda: 'Talk #10',
		pic: 'Speakership Team',
		speakers: [
			{
				name: DATA_SPEAKER['muh-rahmatullah'].name,
				data: DATA_SPEAKER['muh-rahmatullah'],
			},
		],
		topics: 'Flutter',
		title: 'Experimenting with Flutter dynamic render',
		organization: 'Grab',
	},
	{
		uuid: uuidv4(),
		time: '16.00 - 16.30',
		duration: '30',
		agenda: 'Break',
		pic: 'Logistic Team',
		speakers: [],
		title: null,
		organization: '',
	},
	{
		uuid: uuidv4(),
		time: '16.30 - 17.00',
		duration: '30',
		agenda: 'Talk #11',
		pic: 'Speakership Team',
		speakers: [
			{
				name: DATA_SPEAKER['achmad-ilham'].name,
				data: DATA_SPEAKER['achmad-ilham'],
			},
		],
		topics: 'Flutter',
		title: 'Expand your Flutter App on a Foldable Phone',
		organization: 'Dicoding',
	},
	{
		uuid: uuidv4(),
		time: '17.00 - 17.30',
		duration: '30',
		agenda: 'Talk #12',
		pic: 'Speakership Team',
		speakers: [
			{
				name: DATA_SPEAKER['rama-widragama-putra'].name,
				data: DATA_SPEAKER['rama-widragama-putra'],
			},
		],
		topics: 'Flutter',
		title: 'Flutter Adoption in Tokopedia',
		organization: 'Tokopedia',
	},
	{
		uuid: uuidv4(),
		time: '17.30 - 18.00',
		duration: '30',
		agenda: 'Fireside Chat',
		pic: 'Event team',
		speakers: [
			{
				name: 'All Speakers',
				data: null,
			},
		],
		title: null,
		organization: '',
	},
];
